apiVersion: apps/v1
kind: Deployment
metadata:
  name: db
spec:
  replicas: 1
  selector:
    matchLabels:
      app: db
  template:
    metadata:
      labels:
        app: db
    spec:
      containers:
      - name: postgres
        image: <DTR FQDN>:4443/engineering/db:1.0
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: api
  template:
    metadata:
      labels:
        app: api
    spec:
      containers:
      - name: springboot
        image: <DTR FQDN>:4443/engineering/api-build:demo
---
apiVersion: v1
kind: Service
metadata:
  name: database
spec:
  selector:
    app: db
  ports:
  - port: 5432
    targetPort: 5432
---
apiVersion: v1
kind: Service
metadata:
  name: api-ingress
spec:
  type: NodePort
  selector:
      app: api
  ports:
  - port: 8080
    targetPort: 8080
