apiVersion: apps/v1
kind: Deployment
metadata:
  name: api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: api
  template:
    metadata:
      labels:
        app: api
    spec:
      containers:
      - name: springboot
        image: {{ .Values.MSR.FQDN }}:{{ .Values.MSR.port }}/{{ .Values.API.repo }}:{{ .Values.API.tag }}
        readinessProbe:
          httpGet:
            path: /api/products/1
            port: 8080
          initialDelaySeconds: 20
          periodSeconds: 5
      nodeSelector:
        kubernetes.io/hostname: {{.Values.environment.host}}
